version: '3'

services:
  web:
    image: tons/pstackdemo
    build: .
    ports:
      - "80:8000"
    environment:
      SERVER_PORT: 8000
      DEBUG: "True"
      REDIS_HOST: redis
      REDIS_PORT: 6379
  redis:
    image: redis:alpine
